# Generated by Django 5.2 on 2025-07-24 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_alter_run_athlete'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='athlete_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('goals', models.TextField(blank=True)),
                ('weight', models.FloatField(blank=True)),
            ],
        ),
    ]
