# Generated by Django 5.2 on 2025-07-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0004_athleteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
