# Generated by Django 5.2 on 2025-07-25 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0007_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='position', serialize=False, to='app_run.run')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
