# Generated by Django 5.2 on 2025-07-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='id',
        ),
        migrations.AlterField(
            model_name='position',
            name='run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='position', serialize=False, to='app_run.run'),
        ),
    ]
