# Generated by Django 5.2 on 2025-07-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_collectibleitem_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectibleitem',
            old_name='items',
            new_name='users',
        ),
    ]
