# Generated by Django 5.2 on 2025-07-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0016_position_distance_position_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(default=0.0),
        ),
    ]
