# Generated by Django 5.2 on 2025-08-05 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0019_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athleteinfo',
            options={'verbose_name': 'Информация об атлете', 'verbose_name_plural': 'Информация об атлетах'},
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'verbose_name': 'Челлендж', 'verbose_name_plural': 'Челленджи'},
        ),
        migrations.AlterModelOptions(
            name='collectibleitem',
            options={'verbose_name': 'Коллекционный предмет', 'verbose_name_plural': 'Коллекционные предметы'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'verbose_name': 'Забег', 'verbose_name_plural': 'Забеги'},
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.TextField(blank=True, default='', verbose_name='Цели'),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='athlete_info', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to=settings.AUTH_USER_MODEL, verbose_name='Атлет'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Название челленджа'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='picture',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='uid',
            field=models.CharField(max_length=255, unique=True, verbose_name='Уникальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='users',
            field=models.ManyToManyField(related_name='collectible_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Ценность'),
        ),
        migrations.AlterField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='position',
            name='distance',
            field=models.FloatField(default=0.0, verbose_name='Дистанция (км)'),
        ),
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='position',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='app_run.run', verbose_name='Забег'),
        ),
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0.0, verbose_name='Скорость (км/ч)'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_rating', to=settings.AUTH_USER_MODEL, verbose_name='Атлет'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_rating', to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='run',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL, verbose_name='Атлет'),
        ),
        migrations.AlterField(
            model_name='run',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='run',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(default=0.0, verbose_name='Дистанция (км)'),
        ),
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(default=0, verbose_name='Время забега (секунды)'),
        ),
        migrations.AlterField(
            model_name='run',
            name='speed',
            field=models.FloatField(default=0.0, verbose_name='Средняя скорость (км/ч)'),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Забег инициализирован'), ('in_progress', 'Забег начат'), ('finished', 'Забег закончен')], default='init', max_length=50, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Атлет')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'unique_together': {('athlete', 'coach')},
            },
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
